### PR TITLE
Color palette

### PR DESCRIPTION
**Pull request by aginzberg**
Slight change of wording to the feedback section of the task.

Proposed custom gray palette based on the button shadow color discussed today. Other hues derived from some hex arithmetic based on Google MD's specs. This palette allows focus on buttons so tabbing through daemo now has a reasonable user interface.

### CODE REVIEW

**Comment by mbernst** [comment]
n00b question: what is MD's recommended tab focus interaction? Seems weird
that we'd need to invent our own solution.

**Comment by aginzberg** [comment]
Sorry for the confusion. Previously we had overridden the gray palette to make our own custom gray. But in doing so we had set a few of the hues to white which shouldn't have been white but instead should be some shade of gray. MD by default then uses a specific hue from this custom palette as the button focus. This hue we had erroneously set to white, so there appeared to be no focus at all.

Here, I just flush out all of the gray hues in line with https://www.google.com/design/spec/style/color.html so that when MD tries to grab the correct hue on focus, it actually gets one that's not white.

**Comment by mbernst** [comment]
Ah! OK.

**Comment by dmorina** [comment]
@mbernst there is no spec about the actual keyboard tabbing but it should be the same as normal Tabs or buttons (on hover) that's what we are doing now

**Comment by dmorina** [comment]
lgtm

**Comment by dmorina** [comment]
seems to be a 14% background-color property

**Comment by aginzberg** [comment]
returning to default gray. not sure why we needed a custom one to begin with.

**Comment by dmorina** [comment]
looking good

**Pull request merged**
