### PR TITLE
html for worker task portfolio

### PR DESCRIPTION
**Pull request by radhikabhanu**

### CODE REVIEW

**Comment by neilthemathguy** [comment]
Let's synch this up as #252

**Comment by nistala** [comment]
@radhikabhanu can u post a screenshot?

**Comment by dmorina** [comment]
good job guys, do you think you could move the data to angular for now and do an ng-repeat on your worker/home html so that it reduces the amount of code?, and use ng-class with condtions on your data

**Comment by radhikabhanu** [comment]
Here's the screenshot (This layout will be changed, and Angularised)
screen shot 2015-06-11 at 5 46 32 pm

**Comment by dmorina** [comment]
lgtm, @nistala @neilthemathguy any thoughts?

**Comment by neilthemathguy** [comment]
It is great, @radhikabhanu and @karanrajpal  are working on making it consistent with the #246. Please keep this mockup too, we will use it in future.

**Pull request closed without merging**
