### PR TITLE
User profile

### PR DESCRIPTION
**Pull request by radhikabhanu**
1. Making a call to api/profile for user's profile (regardless of whether user is worker or req)
2. Small fix to the UserProfileViewSet

### CODE REVIEW

**Comment by dmorina** [comment]
let's not add bower_components to git

**Comment by radhikabhanu** [comment]
New controller and service for generic user profile
Contributor - Karan Rajpal

**Comment by dmorina** [comment]
see comment above

**Comment by nistala** [comment]
@radhikabhanu @karanrajpal please remove the bower_components from the PR and we can do the review after

**Pull request closed without merging**
