### PR TITLE
#647 Extend data source on authoring page

### LINKED ISSUE #647: extend data_source on authoring page
-allow requester to concatenate static text with column names from the spreadsheet file
something like `This is my question {column1} and this is the expected answer {column2}.`
spaces between `{}` can be ignored and it should highlight the {column}s as code.
data_source should be a list of objects `[{type: 'static', posititon:1, value: 'This is my question '}, {type: 'dynamic', value: 'column_1', ...}]`

this goes into the template_items of the authoring interface (create project) 
further discussions will happen on Slack

### PR DESCRIPTION
**Pull request by Nalinc**
Closes #647.

**Change summary:**
- Allow requesters to use static text with dynamic column names from attached csv file.
- Allow multiple occurrences of the same dynamic field.

Changes are available on https://daemo-develop.herokuapp.com/
Use these credentials to test [user@daemo.com/daemocrowd]

**General use-case(s):**
Question String: "hello {name} welcome to {country}"

 ```
data_sources=[{
     type:'static',
     value:'hello',
     position:0
},{
     type:'dynamic',
     value:'name',
     position:1
},{
     type:'static',
     value:' welcome to ',
     position:2
},{
     type:'dynamic',
     value:'country',
     position:3
}]
 ```
**Screenshots:**
rsz_1

rsz_12

### CODE REVIEW

**Comment by dmorina** [comment]
will push this to this week, need to consult the designers

**Comment by shirishgoyal** [comment]
### Bugs:
##### a) Options not filling in data_source
image


##### b) Options with values from CSV columns not getting updated in tasks
image
Submission page

image
Task Preview

image
Task View


##### c) Link Column not working for url source in Image, Audio and Remote Content Widgets


### Suggested Improvements:
##### a) Add Auto-complete in addition to Link Column
image

**Comment by Nalinc** [comment]
@shirishgoyal: I think the original issue(#647) didn't mention to cover "options" field, so I didn't handle it. Will make changes to cover options field soon. :)

Also, I like the suggestion to include Auto-complete along with Link Column to let users add dynamic fields. However, that would involve few more use-cases like, "should auto-complete show already used columns ?",  And should they have similar functionality as "Link Column" (where clicking an already 'linked 'column will actually 'unlink' it ) ? Addressing such questions is more of a user-preference task.
 
Considering these edge case, may we move auto-complete feature to a new issue ?

**Comment by shirishgoyal** [comment]
Yes we can move auto-complete to new issue. Ignore that for now.

**Comment by Nalinc** [comment]
@shirishgoyal: Covered task "options" to include 'dynamic' as-well-as static tokens. Structure of data_sources is same as the one mentioned in original issue.

**screenshot-1:**
task-authoring

**screenshot-2:**
attempting-task

**Comment by dmorina** [comment]
great @Nalinc we will update it further with improved designs

**Comment by shirishgoyal** [comment]
lgtm

**Comment by shirishgoyal** [comment]
#657 includes this PR as well along with auto-complete.

**Comment by dmorina** [comment]
@Nalinc audio source and image source should be extended too 
please dont add space between static and {column name} before and after but interpret it as the user inputs it, some concatenation cases require that check all the items which accept data_source and apply the same thing

**Comment by dmorina** [comment]
#657 extends this

**Pull request closed without merging**
