### PR TITLE
Adding myself to contributor's page

### PR DESCRIPTION
**Pull request by saviaga**
add yourself to the list of contributors

### CODE REVIEW

**Comment by neilthemathguy** [comment]
you don't need to raise, multiple PRs, could you club all your changes in one.

**Comment by saviaga** [comment]
How do i merger all into one PR?

**Comment by Macbull** [comment]
1. commit all changes to a single branch, 
              a. git checkout -b addingmypage (creates a new branch)
              b. do your changes
              c. git add file1, git add file2 ..........
              d. git commit -m "added myself"
2. push new branch to your forked repo
             git push origin addingmypage
2. create a new pull request for that branch.

PS : Since you will be raising a new pull request, please close this pull request .

**Comment by saviaga** [comment]
Hi: I get an error when trying to push the new brach to my forked repo:

remote: Permission to crowdresearch/crowdsource-platform.git denied to
b57fe9943f1745cda5616879c7f62fbea582edab.
fatal: unable to access '
https://github.com/crowdresearch/crowdsource-platform.git/': The requested
URL returned error:
403

----
The full output of the git shell is this:

C:\Users\Claudia\Documents\GitHub\crowdsource-platform\crowdsource-platform
[saviaga]> git status
On branch saviaga
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   staticfiles/js/crowdsource.routes.js
        modified:   staticfiles/templates/contributors/home.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        staticfiles/images/contributors/saviaga.jpg
        staticfiles/templates/contributors/saviaga.html

no changes added to commit (use "git add" and/or "git commit -a")
C:\Users\Claudia\Documents\GitHub\crowdsource-platform\crowdsource-platform
[saviaga +2 ~2 -0 !]> git add staticfiles/te
mplates/contributors/home.html
C:\Users\Claudia\Documents\GitHub\crowdsource-platform\crowdsource-platform
[saviaga +0 ~1 -0 | +2 ~1 -0 !]> git add sta
ticfiles/templates/contributors/saviaga.html
C:\Users\Claudia\Documents\GitHub\crowdsource-platform\crowdsource-platform
[saviaga +1 ~1 -0 | +1 ~1 -0 !]> git add sta
ticfiles/js/crowdsource.routes.js
C:\Users\Claudia\Documents\GitHub\crowdsource-platform\crowdsource-platform
[saviaga +1 ~2 -0 | +1 ~0 -0 !]> git add sta
ticfiles/images/contributors/saviaga.jpg
C:\Users\Claudia\Documents\GitHub\crowdsource-platform\crowdsource-platform
[saviaga +2 ~2 -0]> git commit -m "Adding my
self to contributor's page"
[saviaga e7b3387] Adding myself to contributor's page
 4 files changed, 21 insertions(+)
 create mode 100644 staticfiles/images/contributors/saviaga.jpg
 create mode 100644 staticfiles/templates/contributors/saviaga.html
C:\Users\Claudia\Documents\GitHub\crowdsource-platform\crowdsource-platform
[saviaga]> git push origin saviaga
fatal: unable to access '
https://github.com/crowdresearch/crowdsource-platform.git/': Failed connect
to github.com:443;
No error
C:\Users\Claudia\Documents\GitHub\crowdsource-platform\crowdsource-platform
[saviaga]> git push origin saviaga
remote: Permission to crowdresearch/crowdsource-platform.git denied to
b57fe9943f1745cda5616879c7f62fbea582edab.
fatal: unable to access '
https://github.com/crowdresearch/crowdsource-platform.git/': The requested
URL returned error:
403

**Pull request closed without merging**
