### PR TITLE
Issue forms

### LINKED ISSUE #637: authentication related forms
-go through the existing forms: login, register, change-password, forgot password; make sure the styling looks right, add ng-messages wherever they are missing

### PR DESCRIPTION
**Pull request by Nalinc**
Closes #637.

**Change summary:**
- Prevent unnecessary server-calls if form is invalid.
- Provide meaningful message(s) to user in case the form-submission returns an error.
- Covers login-form, register-form, forget-password-form, change-password form.
- Use of `ng-submit` on `<form>` instead of `ng-click` on submit buttons. This enables user to submit forms with Return Key(Enter key) too.

Changes are available on https://daemo-develop.herokuapp.com/

**General use-cases:**
- Try submitting a form without entering any input.
- Fill the form partially and leave other fields blank.
- Complete the form with some ambiguity (different values for password and its confirmation).
- Use an existing email while registering(or non existent email in 'forgot-password') to see relevant server side messages.

**Screenshots:**
rsz_change-password
rsz_forgot-password
rsz_register
rsz_login

### CODE REVIEW

**Comment by mbernst** [comment]
Great to see you digging in!

**Comment by Nalinc** [comment]
@mbernst: Thanks professor. I'm looking forward to be a core contributor. You might see more PRs from me in future :)

**Comment by dmorina** [comment]
lgtm

**Comment by shirishgoyal** [comment]
Registration:
a) When initial validation fails from backend, subsequent validations do not turn form into pristine condition. Therefore registration cannot proceed.
image

To replicate:
a) Fill all fields and email with already existing email address in backend
b) Click Signup and it should show email is not unique
c) Change email to a new unique one
d) Now Signup won't work at all even if all fields are correct

**Comment by dmorina** [comment]
looking good

**Pull request merged**
