### PR TITLE
Fixes #593 and few layout issues in different views

### LINKED ISSUE #593: checkbox answer and radio item bugs
-when adding radio button it raises an exception about radio button group missing
-checkbox toggle function doesn't handle properly multiple selected values, neither does handleCheckbox of @aginzberg

### PR DESCRIPTION
**Pull request by shirishgoyal**
- Checkbox selection fixed in initial and returned task
- Radio inclusion in template - angular ctreq issue resolved
- Fix answer shown against label in task monitoring 
- Fix layouts for dashboard, my projects and task view where layout and flex tags caused truncation of parent container

### CODE REVIEW

**Comment by dmorina** [comment]
screen shot 2015-11-20 at 9 21 56 am

**Comment by dmorina** [comment]
Chrome layout issues

**Comment by dmorina** [comment]
Version 46.0.x

**Comment by shirishgoyal** [comment]
Fixed layout problems linked to Chrome v46.x

**Comment by dmorina** [comment]
lgtm

**Pull request merged**
