### PR TITLE
Authoring Advanced Options

### PR DESCRIPTION
**Pull request by shirishgoyal**
Extends #658 

image

image

image

### CODE REVIEW

**Comment by dmorina** [comment]
screen shot 2016-02-19 at 2 36 39 pm

**Comment by dmorina** [comment]
by default we should hide this information, see the issue description, and defaults seem a bit unrealistic same day and 10 minutes

**Comment by dmorina** [comment]
also resolve conflicts

**Comment by shirishgoyal** [comment]
- Advanced options hidden by default now
- Removed default values

**Comment by dmorina** [comment]
screen shot 2016-03-04 at 10 27 58 am

some tiny css issue

**Pull request merged**
