### PR TITLE
Markdown based instructions

### PR DESCRIPTION
**Pull request by shirishgoyal**
screenshot-localhost 8000 2016-09-07 13-31-22

- Upgrade Angular-Material
- Add markdown to instructions
- Show instructions in markdown, images and audio elements in project review submission
- Fix user profile bug for unspecified options and birthday field
- Change text tooltip for "Text" to "Text Input"

### CODE REVIEW

**Comment by mbernst** [comment]
What did the upgrade of Angular Material do?

**Comment by shirishgoyal** [comment]
@mbernst https://github.com/angular/material/blob/master/CHANGELOG.md

**Comment by mbernst** [comment]
"Fix animations for Input messages, Autocomplete, Dialog" <-- did this fix
our weird floating bugs?

**Comment by dmorina** [comment]
i dont think so, there is a fix in a different branch which should take care of those issues though

**Pull request merged**
