### PR TITLE
Unauthenticated routes change issue

### PR DESCRIPTION
**Pull request by shirishgoyal**
Issue by @jsilver
i tried https://lit-hollows-1533.herokuapp.com/task-feed and https://lit-hollows-1533.herokuapp.com/ both auto-redirect to https://lit-hollows-1533.herokuapp.com/login --do you expect this to happen? ... https://lit-hollows-1533.herokuapp.com/task-feed shows "No free tasks available" for a second then shows this Login box (this is the actual page). notice the whitespace on the right (see image/Slack link). 

@shirish
Also all the links - which need user to be logged in, still show the view instead of asking user to login first.

Resolved

### CODE REVIEW

**Comment by mbernst** [comment]
I know many web frameworks have built in auth_require modules. Just checking here: does ng have one? I'm surprised you needed to write your own!

**Comment by shirishgoyal** [comment]
Angular.js doesn't provide any such module as it allows complete flexibility for implementation. 
Using ng-router, we are quite limited in how we can implement it and therefore, we had to add the checks both in interceptor and router change event.

**Comment by dmorina** [comment]
Lgtm

**Comment by mbernst** [comment]
wow, that's nuts it's not a builtin

**Comment by shirishgoyal** [comment]
I prefer though that it is not built in. Frontend depends on backend for authentication so it should be flexible enough to allow different security layers and approaches.

**Comment by neilthemathguy** [comment]
lgtm.

**Comment by mbernst** [comment]
Thanks!

On Tuesday, September 1, 2015, neilthemathguy <notifications@github.com>
wrote:

> lgtm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crowdresearch/crowdsource-platform/pull/468#issuecomment-136897257>
> .
>


-- 
sent from my NLS

**Comment by nistala** [comment]
lgtm

**Pull request merged**
