### PR TITLE
Adding MTurk Hits data scraped from web.

### PR DESCRIPTION
**Pull request by agarwal22megha**
API Reference: https://crowd-power.appspot.com/_ah/api/mturk/v1/hitgroup/search

### CODE REVIEW

**Comment by nistala** [comment]
@agarwal22megha should this PR contain some json?

**Comment by agarwal22megha** [comment]
Hey Rohit, the file is in json format. Sorry but am I missing out something?

**Comment by neilthemathguy** [comment]
LGTM

**Comment by neilthemathguy** [comment]
Enhancement: Transform the raw data to fit current data models.

**Pull request merged**
