### PR TITLE
Adding myself to contributor's page

### PR DESCRIPTION
**Pull request by amandhapola**

### CODE REVIEW

**Comment by neilthemathguy** [comment]
Could you please sign the Contributor License Agreement. Thank you!

**Comment by amandhapola** [comment]
Done . Signed the Contributor License Agreement.

**Comment by dmorina** [comment]
can you leave the migrations out of this pr?

**Comment by neilthemathguy** [comment]
Taking this PR out of the pending list.  Please fix the bugs and raise the new PR or move to the Milestone 2. Thank you.

**Pull request closed without merging**
