### PR TITLE
Authentication fix

### PR DESCRIPTION
**Pull request by dmorina**
@nistala we are rolling back to Session Auth until we have the middleware to encrypt oauth cookies, oauth2 is supported as well

@aginzberg can you test?

### CODE REVIEW

**Comment by Macbull** [comment]
@dmorina : just to confirm,just before this PR, request.user was always Anonymous . Right ??

**Comment by dmorina** [comment]
Hey, only if you weren't logged in, if yes then it wasn't Anonymous

**Comment by mbernst** [comment]
I'm out of date. Was this addressed with the recent logged-in check PR?

**Comment by dmorina** [comment]
@mbernst no, this is a different question, when unauthenticated the backend will return Anonymous when trying to access `request.user`, this is a non-issue

**Pull request merged**
