### PR TITLE
Commited new changes & adding myself to contributor's page

### PR DESCRIPTION
**Pull request by vineetsethia**
Adding myself to contributor's page!

### CODE REVIEW

**Comment by nistala** [comment]
Please merge changes from closed PRs into this PR.

**Comment by neilthemathguy** [comment]
The route is missing, Could you take a look? Thanks!

**Comment by vineetsethia** [comment]
Updated 2 files-crowdsource.routes.js & home.html

**Comment by vineetsethia** [comment]
is this okay,sir! or anything i should taken care of ?

**Comment by vineetsethia** [comment]
it hasn't been merged yet sir.is there anything wrong with this pull request @nistala & @neilthemathguy .please,tell me if there is any correction,i have to make.thanks :)

**Comment by neilthemathguy** [comment]
Duplicate #173

**Pull request closed without merging**
