### PR TITLE
Adding myself to Contributor's list

### PR DESCRIPTION
**Pull request by riyakothari**

### CODE REVIEW

**Comment by dmorina** [comment]
fix your merge conflicts please

**Comment by riyakothari** [comment]
It shows no conflicts.

**Comment by gkovacs** [comment]
@riyakothari there are merge conflicts - I think your branch is out of sync with the main develop2 branch. try pulling from the develop2 branch on https://github.com/crowdresearch/crowdsource-platform and then fix the merge conflicts that emerge.

**Comment by nistala** [comment]
@riyakothari i think you need to merge develop2, you've removed conflicts but the branch is still not merged correctly.

**Pull request closed without merging**
