### PR TITLE
Added autofocus for first fields of login and register templates

### PR DESCRIPTION
**Pull request by insomniac12**
Pull request for  #634

### CODE REVIEW

**Comment by dmorina** [comment]
resolve conflicts please, lgtm otherwise

**Comment by shirishgoyal** [comment]
This commit won't solve the problem completely as it requires directive approach for Angular. It will only work when page is loaded initially on login/register URLs.

**Comment by dmorina** [comment]
agreed

**Comment by dmorina** [comment]
@insomniac12 you may close this

**Pull request closed without merging**
