### PR TITLE
added myself to the contributors

### PR DESCRIPTION
**Pull request by rcompt**

### CODE REVIEW

**Comment by neilthemathguy** [comment]
routes home.html  are missing, could you check.

**Comment by rcompt** [comment]
I can see home.html within the contributors folder, but not sure what you mean by routes?

**Comment by Macbull** [comment]
For this task, you need to change 4 files (home.html, crowdsource.routes.js, <yourpage>.html, <yourImage>.jpg) . For help, go through "Example: Hello World Tutorial" section of http://crowdresearch.stanford.edu/w/index.php?title=GettingStarted

If you still have any problem, feel free to post it on slack or here itself.

**Comment by nistala** [comment]
LGTM

**Pull request merged**
