### PR TITLE
Resolves Link change password #439

### PR DESCRIPTION
**Pull request by shirishgoyal**
image

menu_579

### CODE REVIEW

**Comment by dmorina** [comment]
lgtm++

**Comment by aginzberg** [comment]
link looks great :) we just need request.data['admin_override'] = True in the change_password method since we locked down registration.

**Comment by dmorina** [comment]
that to be fixed in a following pr by @aginzberg 
this pr is good to be merged

**Comment by aginzberg** [comment]
yes will get to change password shortly

**Pull request merged**
