### PR TITLE
adding oauth2client to requirements.txt

### PR DESCRIPTION
**Pull request by uwecerron**
Adding missing module required to run the project.

### CODE REVIEW

**Comment by dmorina** [comment]
Reason?

**Comment by dmorina** [comment]
It's in the django-oauth-toolkit, no need for this

**Comment by uwecerron** [comment]
It was throwing an error when i pulled develop2 branch.

**Comment by dmorina** [comment]
Post your pip freeze here and the error message

**Comment by dmorina** [comment]
Make sure pip install is successful because everything you need it there

**Comment by uwecerron** [comment]
You are right, had to destroy my vagrant box and reload it again. weird. sorry about that.

**Comment by dmorina** [comment]
No problem

**Pull request closed without merging**
