### PR TITLE
Adding to contributor's

### PR DESCRIPTION
**Pull request by riyakothari**

### CODE REVIEW

**Comment by neilthemathguy** [comment]
home.html is missing. Could you test the code?

**Comment by riyakothari** [comment]
@neilthemathguy,  Sir now is there any problem in the code that my merge request hasn't been accepted??

**Comment by dmorina** [comment]
There seem to be some conflicts, please resolve them

**Comment by pemmasanikrishna** [comment]
Upload your image rather than including its link from github.

**Comment by riyakothari** [comment]
I tried to upload it instead of the github link,but it did not show the image in the preview, It only showed the code. That's why I used the github link... Can you help me out here?

**Comment by pemmasanikrishna** [comment]
Are you using windows platform ? If yes , then go for github for windows, it has GUI and its easy to use. What problem are you facing actually?

**Comment by riyakothari** [comment]
I got it ,thank you,@pemmasanikrishna

**Comment by pemmasanikrishna** [comment]
I think still there are merge conflicts. Once check that

**Comment by neilthemathguy** [comment]
Taking this PR out of the pending list.  Please fix the bugs/resolve conflicts and raise the new PR or move to the Milestone 2. Thank you.

**Pull request closed without merging**
