### PR TITLE
Adding myself to contributor's page

### PR DESCRIPTION
**Pull request by Milstein**

### CODE REVIEW

**Comment by nistala** [comment]
LGTM

**Comment by Milstein** [comment]
Is there any conflict! @nistala

**Comment by nistala** [comment]
@Milstein still can't merge automatically, can you merge with crowdresearch:develop2? it is possible that PRs have been merged since your changes have been committed, which requires the manual merge.

**Comment by Milstein** [comment]
@nistala even I am not able to merge it!

**Comment by nistala** [comment]
@Milstein you will not be able to merge, you need to fetch upstream changes and merge locally first. Then you should push to your branch, which will make it mergeable here.

**Pull request merged**
