### PR TITLE
Ui rating bugfix

### PR DESCRIPTION
**Pull request by nistala**
#472 
- Fix flicker, show loading screen

### CODE REVIEW

**Comment by dmorina** [comment]
when you PUT to /worker-requester-rating/:id you dont have to do a GET /rating/requesters_reviews

**Comment by dmorina** [comment]
same goes for POST

**Comment by nistala** [comment]
@dmorina  what if the request fails?

**Comment by dmorina** [comment]
If request fails you don't update anything on the ui, just notify the user

**Comment by dmorina** [comment]
if not updated #485 will fix this fully

**Comment by dmorina** [comment]
is it ok to close this?

**Comment by nistala** [comment]
closing due to removing immediate feedback to user.

**Pull request closed without merging**
