### PR TITLE
CSRF Referrer Checking for specific domains

### PR DESCRIPTION
**Pull request by shirishgoyal**
Disable referrer checking for HTTPS requests till domain redirection issue is handled

### CODE REVIEW

**Comment by dmorina** [comment]
we dont have to disable it just allow a list of origins to be configured in settings

**Comment by shirishgoyal** [comment]
Ok. Will tweak it to handle a list of domains from settings.

**Comment by shirishgoyal** [comment]
#497 CSRF referrer check is done against specific domains in settings.

Resolved

**Comment by dmorina** [comment]
lgtm, did you manage to set up a test for this?

**Comment by shirishgoyal** [comment]
Manual test will need SSL setup and domain redirection. I guess we can do away with it for now as it only handles CSRF issue.

**Comment by dmorina** [comment]
lgtm, resolve conflicts please

**Comment by dmorina** [comment]
lgtm

**Comment by aginzberg** [comment]
lgtm

**Pull request merged**
