### PR TITLE
Project persistence with localstorage

### PR DESCRIPTION
**Pull request by shirishgoyal**

### CODE REVIEW

**Comment by dmorina** [comment]
we will return to these, atm low priority, thanks

**Comment by dmorina** [comment]
code lgtm
Im for using local storage, user data that is stored atm in the cookies should be moved to LS
however task authoring should store data in the backend as partial draft project

**Comment by dmorina** [comment]
@aginzberg could you have a look? thanks

**Comment by aginzberg** [comment]
oooh, very nice! lgtm

**Pull request merged**
